name: QuotescEnv
channels:
  - anaconda
  - conda-forge
  - pypi
  - pytorch
dependencies:
  - python=3.7
  - python-telegram-bot=12.2.0
  - requests=2.22.0
  - requests-oauthlib=1.0.0
  - pyyaml=5.1.2